import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Star } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useStore } from "@/lib/store";
import { useProducts } from "@/services/hooks";
import { reviewService } from "@/services";
export const Route = createFileRoute("/account/reviews")({ head: () => ({ meta: [{ title: "Đánh giá và phản hồi — MỘC" }, { name: "description", content: "Chia sẻ đánh giá về sản phẩm đã mua tại MỘC." }, { property: "og:title", content: "Đánh giá và phản hồi — MỘC" }, { property: "og:description", content: "Chia sẻ trải nghiệm về trang phục MỘC của bạn." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Reviews });
function Reviews() { const store = useStore(); const [ratings, setRatings] = useState<Record<string, number>>({}); const [texts, setTexts] = useState<Record<string, string>>({}); const [submitted, setSubmitted] = useState<string[]>([]); const [error, setError] = useState(""); const all = useProducts(); const items = ["dam-midi-lina", "ao-so-mi-ella"].map(id => all.find(p => p.id === id)); return <><h2 className="text-2xl font-medium mb-2">Đánh giá & phản hồi</h2><p className="text-sm text-muted-foreground mb-8">Chia sẻ cảm nhận về những sản phẩm bạn đã mua.</p><div className="space-y-6">{items.filter(Boolean).map(p => { if (!p) return null; return <article key={p.id} className="border border-border p-5 md:p-7"><div className="flex gap-5 border-b pb-5"><Link to="/products/$productId" params={{ productId: p.id }}><img src={p.image} alt={p.name} className="w-20 h-25 object-cover"/></Link><div><Link to="/products/$productId" params={{ productId: p.id }} className="font-medium hover:underline">{p.name}</Link><p className="text-xs text-muted-foreground mt-2">Đơn hàng đã hoàn tất</p><Link to="/products/$productId" params={{ productId: p.id }} className="text-xs text-accent mt-3 block">Xem chi tiết sản phẩm →</Link></div></div>{submitted.includes(p.id) ? <p className="text-sm text-accent pt-5">Cảm ơn bạn đã gửi đánh giá!</p> : <div className="pt-5"><p className="text-sm font-medium mb-3">Bạn thấy sản phẩm thế nào?</p><div className="flex gap-1 mb-5">{[1,2,3,4,5].map(star => <Button key={star} variant="ghost" size="icon" className="size-8 p-0" aria-label={`Đánh giá ${star} sao`} onClick={() => setRatings({ ...ratings, [p.id]: star })}><Star className={`size-6 ${star <= (ratings[p.id] || 0) ? "fill-accent text-accent" : "text-muted-foreground"}`}/></Button>)}</div><textarea value={texts[p.id] || ""} onChange={e => setTexts({ ...texts, [p.id]: e.target.value })} maxLength={1000} placeholder="Chia sẻ cảm nhận của bạn về sản phẩm..." className="w-full border border-border p-3 text-sm min-h-28 outline-none focus:border-accent resize-y"/>{error === p.id && <p className="text-xs text-destructive mt-2">Vui lòng chọn số sao và nhập ít nhất 10 ký tự đánh giá.</p>}<Button className="mt-4" onClick={() => { if (!ratings[p.id] || (texts[p.id] || "").trim().length < 10) { setError(p.id); return; } setError(""); void reviewService.create({ productName: p.name, customer: "Nguyễn Thị Minh Anh", rating: ratings[p.id] ?? 5, text: (texts[p.id] || "").trim() }).then(() => { setSubmitted(cur => [...cur, p.id]); store.notify("Đã gửi đánh giá thành công"); }); }}>Gửi đánh giá</Button></div>}</article>; })}</div></>; }
